Replace getopt with POSIX compliant alternative
BSD doesn't provide getopt.

Resolves #10 #18

diff --git a/sudo b/sudo
--- a/sudo
+++ b/sudo
@@ -18,38 +18,64 @@ help() {
 	EOF
 }
 
+die() {
+	echo "sudo: $1" >&2
+	help >&2
+	exit 1
+}
+
+set_user() {
+	case "${2-}" in
+		'' | -- | '#') die "option '$1' requires an argument" ;;
+		*) user=${2#\#} ;;
+	esac
+}
+
 if [ $# -eq 0 ]; then
 	help >&2
 	exit 1
 fi
-
-# Note: "+" disables optional option parameters
-opts=$(getopt -n sudo -o +insu:h -l login,non-interactive,shell,user:,help -- "$@") || {
-	help >&2
-	exit 1
-}
-eval set -- "$opts"
 
 flag_i=
 flag_n=
 flag_s=
 user=
 while [ $# -gt 0 ]; do
-	case "$1" in
-		-i | --login) flag_i='-i';;
-		-n | --non-interactive) flag_n='-n';;
-		-s | --shell) flag_s='-s';;
-		-u | --user) user=${2#\#}; shift;;
-		-h | --help) help; exit 0;;
-		--) shift; break;;
+	case $1 in
+		-i | --login) flag_i='-i' ;;
+		-n | --non-interactive) flag_n='-n' ;;
+		-s | --shell) flag_s='-s' ;;
+		-h | --help) help; exit 0 ;;
+		-u | --user) set_user "$1" "${2-}"; shift ;;
+		--user=*) set_user '--user' "${1#--user=}" ;;
+		--) shift; break ;;
+		--*) die "unrecognized option '$1'" ;;
+		# Parse clustered short options (e.g. -ins, -uuser).
+		-?*)
+			opts=${1#-}
+			while [ "$opts" ]; do
+				case "$opts" in
+					i*) flag_i='-i' ;;
+					n*) flag_n='-n' ;;
+					s*) flag_s='-s' ;;
+					h*) help; exit 0 ;;
+					u*)
+						if [ "$opts" != 'u' ]; then
+							set_user '-u' "${opts#u}"; break
+						else
+							set_user '-u' "${2-}"; shift
+						fi ;;
+					*) die "invalid option -- '${opts%"${opts#?}"}'" ;;
+				esac
+				opts=${opts#?}
+			done ;;
+		*) break ;;
 	esac
 	shift
 done
 
-if [ "$flag_i" ] && [ "$flag_s" ]; then
-	echo "sudo: you may not specify both the '-i' and '-s' options" >&2
-	exit 1
-fi
+[ "$flag_i" ] && [ "$flag_s" ] \
+	&& die "you may not specify both the '-i' and '-s' options"
 
 _doas() {
 	exec doas $flag_n ${user:+-u "$user"} "$@"
